# data configuration options
#
#
---
data_path: "/home/jniles/code/drugdb/data/"
db: "/home/jniles/code/drugdb/db/drug.db"
schema: "/home/jniles/code/drugdb/db/schema"
email_dir: "/home/jniles/code/drugdb/mail/"

# parameters for consumption projections

# hindsight - number of days of prior consumption
# data to take into account to project remaining
# time.
hindsight: 90

# minimum - sets the minimum number of days
# for drug consumption.  If the supply of drugs
# will not last past this minimum, the email system
# will throw a warning
minimum: 30

# email configuration
# Uncomment for the NCF network
email: {
  sender: "admin@drugdb"
  #via: :smtp,
  #via_options: {
  #  address: "smtp.ncf.edu",
  #  port: "25",
  #  authentication: :plain,
  #  domain: "10.10.11.15"
  #}
}
