# data configuration options
---

# This is the top level install directory from which all
# other paths in the application are formed.
install_dir: "C:/Users/Vinushka/Documents/GitHub/newPP/Planned-Parenthood-Drug-Inventory/"

# parameters for consumption projections

# hindsight - number of days of prior consumption
# data to take into account to project remaining
# time.
hindsight: 90

# minimum - sets the minimum number of days
# for drug consumption.  If the supply of drugs
# will not last past this minimum, the email system
# will throw a warning
minimum: 30

# email configuration
# Uncomment for the NCF network
email:
 - 
  sender: "admin@drugdb"
  admin: "stefan.schalk12@ncf.edu"
  via: :smtp
  via_options: 
   - 
    :address: "smtp.ncf.edu"
    :port: "25"
    :authentication: :plain
    :domain: "10.10.11.15"
